// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone"], function(Backbone) {
    var HITTableView;
    return HITTableView = (function(_super) {

      __extends(HITTableView, _super);

      function HITTableView() {
        return HITTableView.__super__.constructor.apply(this, arguments);
      }

      HITTableView.prototype.title = "";

      HITTableView.prototype.columns = {
        title: {
          header: "Title"
        },
        hitid: {
          header: "HIT Id"
        },
        number_assignments_available: {
          header: "Left"
        },
        max_assignments: {
          header: "Max"
        },
        number_assignments_completed: {
          header: "Done"
        },
        expiration: {
          header: "Expires",
          draw: function(model) {
            return new Date(model.get("expiration")).toISOString();
          }
        }
      };

      HITTableView.prototype.pagination = false;

      HITTableView.prototype.size = 5;

      return HITTableView;

    })(Backbone.TableView);
  });

}).call(this);
