// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    paths: {
      jquery: "libs/jquery",
      underscore: "libs/underscore",
      backbone: "libs/backbone",
      text: "libs/text",
      cs: "libs/cs",
      bootstrap: "libs/bootstrap",
      highcharts: "libs/highcharts",
      exporting: "libs/exporting",
      dropdown: "libs/bootstrap-dropdown",
      collapse: "libs/bootstrap-collapse",
      nod: "libs/nod",
      dotimeout: "libs/jquery.dotimeout.min"
    },
    shim: {
      bootstrap: ["jquery"],
      dropdown: ["bootstrap"],
      collapse: ["bootstrap"],
      highcharts: {
        deps: ["jquery"],
        exports: "Highcharts"
      },
      exporting: {
        deps: ["highcharts"]
      },
      nod: ["jquery"],
      dotimeout: ["jquery"],
      backbone: {
        deps: ["underscore", "jquery"],
        exports: "Backbone"
      },
      underscore: {
        exports: "_"
      }
    }
  });

  require(["jquery", "app", "highcharts", "exporting", "bootstrap", "dropdown", "collapse", "dotimeout", "nod"], function($, App, Highcharts, Exporting) {
    return App.initialize();
  });

}).call(this);
