// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'backbone', 'text!templates/run-expt-modal.html'], function($, Backbone, RunExptTemplate) {
  var RunExptView, _ref;

  return RunExptView = (function(_super) {
    __extends(RunExptView, _super);

    function RunExptView() {
      _ref = RunExptView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    RunExptView.prototype.initialize = function() {
      return this.render();
    };

    RunExptView.prototype.render = function() {
      var runExptTemplate;

      runExptTemplate = _.template(RunExptTemplate, {
        n_assignments: this.options.config.get("HIT Configuration").max_assignments,
        reward: this.options.config.get("HIT Configuration").reward,
        duration: this.options.config.get("HIT Configuration").duration,
        title: this.options.config.get("HIT Configuration").title
      });
      return $('#run-expt-body').html(runExptTemplate);
    };

    return RunExptView;

  })(Backbone.View);
});
