// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['underscore', 'backbone'], function(_, Backbone) {
  var AtAGlanceModel, _ref;

  return AtAGlanceModel = (function(_super) {
    __extends(AtAGlanceModel, _super);

    function AtAGlanceModel() {
      _ref = AtAGlanceModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AtAGlanceModel.prototype.url = '/at_a_glance_model';

    AtAGlanceModel.prototype.defaults = {
      balance: "-"
    };

    return AtAGlanceModel;

  })(Backbone.Model);
});
