// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['underscore', 'backbone'], function(_, Backbone) {
  var ChartModel, _ref;
  return ChartModel = (function(_super) {
    __extends(ChartModel, _super);

    function ChartModel() {
      _ref = ChartModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ChartModel.prototype.url = '/participant_status';

    ChartModel.prototype.defaults = {
      debriefed: 0,
      started: 0,
      completed: 0,
      total: 0,
      credited: 0,
      allocated: 0,
      quit_early: 0
    };

    return ChartModel;

  })(Backbone.Model);
});
