// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['underscore', 'backbone'], function(_, Backbone) {
  var ConfigModel, _ref;
  return ConfigModel = (function(_super) {
    __extends(ConfigModel, _super);

    function ConfigModel() {
      _ref = ConfigModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ConfigModel.prototype.url = '/dashboard_model';

    ConfigModel.prototype.defaults = {
      "AWS Access": {
        aws_access_key_id: "YourAccessKeyId",
        aws_secret_access_key: "YourSecreteAccessKey"
      },
      "HIT Configuration": {
        title: "Perceptual Reaction Time",
        description: "Make a series of perceptual judgments.",
        keywords: "Perception, Psychology",
        question_url: "http://localhost:22362/mturk",
        max_assignments: 10,
        hit_lifetime: 24,
        reward: 1,
        duration: 2,
        us_only: true,
        approve_requirement: 95,
        using_sandbox: true
      },
      "Database Parameters": {
        database_url: "sqlite:///participants.db",
        table_name: "turkdemo"
      },
      "Server Parameters": {
        host: "localhost",
        port: 22362,
        cutoff_time: 30,
        support_ie: true,
        logfile: "server.log",
        loglevel: 2,
        debug: true,
        login_username: "examplename",
        login_pw: "examplepassword"
      },
      "Task Parameters": {
        code_version: 1.0,
        num_conds: 1,
        num_counters: 1
      }
    };

    return ConfigModel;

  })(Backbone.Model);
});
