// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["backbone"], function(Backbone) {
  var HIT, _ref;
  return HIT = (function(_super) {
    __extends(HIT, _super);

    function HIT() {
      _ref = HIT.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HIT.prototype.defaults = {
      status: "",
      number_assignments_available: "",
      number_assignments_completed: "",
      hitid: "",
      max_assignments: 0,
      title: "",
      number_assignments_pending: 0,
      creation_time: "",
      number_assignments_completed: 0,
      expiration: ""
    };

    return HIT;

  })(Backbone.Model);
});
