// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["backbone"], function(Backbone) {
  var Worker, _ref;

  return Worker = (function(_super) {
    __extends(Worker, _super);

    function Worker() {
      _ref = Worker.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Worker.prototype.defaults = {
      "assignmentId": "",
      "workerId": "",
      "accept_time": "",
      "hitid": "",
      "submit_time": ""
    };

    return Worker;

  })(Backbone.Model);
});
